Benz006:
  target: dev
  outputs:
    dev:
      type: postgres
      host: dev.cphyvekdk1wt.us-west-2.rds.amazonaws.com
      user: masteruser
      password: bryte123
      port: 5432
      dbname: dev
      schema: abc
      threads: 4
      keepalives_idle: 0 # default 0, indicating the system default
      connect_timeout: 10 # default 10 seconds